### ISSUE TITLE
No issue but question

### ISSUE THREAD

**Issue by JasonHough75** [nbelyh/VisioOnlineSpfxWebPart#1]
Great SPFX web part btw , it works lovely... is there a way to remove all toolbars and the magnifier etc from the Visio part ? I can see that you can remove toolbars but I cannot seem to be able to find it. Any ideas ?

**Comment by nbelyh** [comment]
Now this is supported out of the box, with a toggle! The line that implements it is here:
https://github.com/nbelyh/VisioOnlineSpfxWebPart/blob/372ddc19e2cee5ba3bc756e39b07878f0f92e6f3/src/WebPart/TopFrame.tsx#L27

**Comment by nbelyh** [comment]
Closing as really old one :)
