### ISSUE TITLE
Very good but missing features wished

### ISSUE THREAD

**Issue by jjs83** [nbelyh/VisioOnlineSpfxWebPart#3]
Hello,
Sorry for my bad english.
This is a very fine tools
For it to be used in my company (by paying a license) it would be necessary: go back / go next buttons and the possibility of making a link on another Visio file by also indicating the page. That would be the best!!

**Comment by nbelyh** [comment]
Hello @jjs83 thank you for the feedback!
I think you can use hyperlinks in Visio diagrams to link to another page, and back-forward browser buttons?
In Visio, you could just set a Hyperlink for a shape, and then navigate back. Am I missing something.

Could you maybe post a screenshot of what you mean?

Also, there is currently no paid license (it's free)

**Comment by jjs83** [comment]
Hi,

Sorry for by bad english, but I am french.
Thanks for your quick return. My question was about your "SharePoint Diagram Frame WebPart":
Links to other pages work fine in the same document, but they don't work at all when calling another document (see screen below)
It's also like this in the internal SharePoint viewer.

In addition, my 2nd question (or suggestion) concerned an improvement which could make it possible to have the equivalent of the "Back" or "Previous" buttons of the browsers to pass more easily from pages to others.

Thanks
JJ SINET

**Comment by nbelyh** [comment]
Yes, now I understand the idea. The issue is, the webpart is running in IFRAME. BUT. This feature does not seem to be impossible, we just need to render another Visio file in the same IFRAME (the linked one) and provide navigation inside the web part.
I will try to implement this feature but for now, have no estimated timeframe.

**Comment by jjs83** [comment]
OK thank you very much 😁

JJ SINET
________________________________

**Comment by nbelyh** [comment]
@jjs83 
This should be implemented in 1.2 ("enable navigation" checkbox)
You need to make a link to antoher visio file (either relative link or a link to a file in SharePoint).
If you make a relative link, the file it refers to should be in the same location in SharePoint as on your local drive.

The checkbox adds the "breadcrumb" trail at the top for the navigation, and allows single-click jumps if a shape is linked to another diagram. This works quick for pages, but is not really quick for diagrams, and I have seen several cases when it just stops at "loading". If it happens need to click on the crumb trail again, then it loads.

![image](https://user-images.githubusercontent.com/528366/215274569-5914ee9e-6982-490f-9d24-58b35272643a.png)

Would appreciate if you could check it out (currently in 1.2 pre-release).

**Comment by nbelyh** [comment]
The 1.2 version should include navigation support to some extent that should cover the basic scenario of files hierarchy.
