### ISSUE TITLE
Current Visio vsdx version not supported

### ISSUE THREAD

**Issue by jonnyfrizz** [nbelyh/VisioOnlineSpfxWebPart#5]
I cannot find any vsdx files in the document library

![image](https://user-images.githubusercontent.com/105042513/167096945-628ac93c-e4bd-4efb-bc00-7caa04262af7.png)

When I use a link I get the following error:

![image](https://user-images.githubusercontent.com/105042513/167089621-7cc6a1a0-aaaa-4eb0-8042-3d52e09a6f51.png)

**Comment by nbelyh** [comment]
H! Pelase note that this add-in is basically just a wrapper for the Visio Online (with some additional capabilities). Can you open the same file in the browser when you just click it?

**Comment by jonnyfrizz** [comment]
Yes that works. 
If I download the vsdx file and upload it again via the webpart, then the file is displayed.

**Comment by nbelyh** [comment]
Looks lie URL issue, or picker. Is the side using German locale ("Dokumente"?) I will check for German, for now verified only for English actually.

**Comment by jonnyfrizz** [comment]
Correct. The sharepoint is set to German.

**Comment by nbelyh** [comment]
Most probably it's the library name (i.e. "Dokumente" instead of "Shared Documents"). I will check and hopefully come back with a 
fix 😄

**Comment by nbelyh** [comment]
The mess with document libraries / names should be fixed in version 1.1
The upload should target the correct library
