### ISSUE TITLE
nbelyh / VisioOnlineSpfxWebPart: Disable VISIO Diagram Scroll bar not possible

### ISSUE THREAD

**Issue by schneika** [nbelyh/VisioOnlineSpfxWebPart#6]
is it possible to disable the Scrollbar in the Diagram Webpart?

[nbelyh](https://github.com/nbelyh)
/
[VisioOnlineSpfxWebPart](https://github.com/nbelyh/VisioOnlineSpfxWebPart)

**Comment by nbelyh** [comment]
The overflow scrollbar should be disabled now (1.1 release).
The built-in Visio scrollbar is unfortunatelly controlled by Visio services and cannot be removed.
You can remove the frame/border though.

**Comment by nbelyh** [comment]
The built-in Visio scrollbar actually CAN be removed, you can **disable PAN** to get rid of it.
