### ISSUE TITLE
Visio is not showing the last version of the file

### ISSUE THREAD

**Issue by ACSirus** [nbelyh/VisioOnlineSpfxWebPart#7]
When you change the vdsx file that is being used by the web part, the changes don't reflect in the already active web parts.
In other words. Every time you change the vdsx file, you also need to remove and re-add the diagram web parts that are using this file.

**Comment by nbelyh** [comment]
Thank you for reporting. Will try to reproduce/fix. Currently on vacations so may take a bit :)

**Comment by ACSirus** [comment]
Thanks! Enjoy your vacation!

Some extra info:

- Version: 1.0.399 

- Both site page and visio file are on the same site.

- File is selected by navigating to it in the document library, not using the link or upload option (Link option is leaving the web part blank btw).

![image](https://user-images.githubusercontent.com/77774675/180370282-d5b1d4f9-6ec2-468f-9301-ecea2d6a137e.png)

**Comment by ACSirus** [comment]
Hi @nbelyh,
Hope you had a wonderful vacation. Just wanted to check in with you if you have had some time to look into this already :)

**Comment by nbelyh** [comment]
This should be fixed in version 1.1 (to be released in the marketplace soon as well)
Before, the upload was creating a copy of the in /SiteAssets library and using that, now it should be the file directly.
